### ISSUE TITLE
Combinar archivos JS - lo hice en la rama anterior "issue/4-refactorizar"

### ISSUE THREAD

**Issue by nosoycesaros** [leoperezx/api-clima#5]
## 👋 Descripción
* Mover el contenido de `clock.js` a `index.js` para manejar todo el JS en un solo archivo.
* Eliminar el import de `clock.js` en `index.html`

**Comment by leoperezx** [comment]
lo hice en la rama anterior "issue/4-refactorizar"

**Comment by nosoycesaros** [comment]
solved in PR #10
